### PR TITLE
Require `FunctionMap` to be passed functions

### PR DESCRIPTION
**Pull request by JeffFessler**
Untested...
Hopefully would address secondary issue buried within #185.

### CODE REVIEW

**Comment by fredrikekre** [comment]
This would disallow callable types, right? You would need to pass `LinearMap(x -> A(x))` after this change.

**Comment by JeffFessler** [comment]
> This would disallow callable types, right? You would need to pass `LinearMap(x -> A(x))` after this change.

Right.  Are there use-cases for that?  (The CI doesn't test for them.)
It's OK to close this little PR if the preference is to stay with duck typing.

**Comment by dkarrasch** [comment]
I'm not sure we want this. First, it's technically breaking, and by callable types, one can image, for instance, `LinearMap`s. They get special treatment and get wrapped, but other people could have

```julia
struct CumSum
    n::Int
end
CumSum(x::AbstractVector) = cumsum(x) # up to size checking
```

to adopt our favourite example from the tests. In fact, I should perhaps add such a callable type to the tests.

Second, the `eltype` parameter in curly brackets has important precedence in the Julia language, and its usage is very similar to ours:

```julia
x = Vector{Int}(undef, 10)
```

The reason is that `T` is the first type parameter, and those are always written in curly brackets after the constructor.

**Comment by JeffFessler** [comment]
ok

**Pull request closed without merging**
