### PR TITLE
Fix links to documentation

### PR DESCRIPTION
**Pull request by tknopp**
they were pointing to nowhere

### CODE REVIEW

**Comment by dkarrasch** [comment]
Thanks. That got messed up when moving the package to JuliaLinearAlgebra. I assume now any reference to @Jutho's account is wrong, isn't it? I see more of those references in the CI/build status and code coverage in the README and in the doc's `make.jl`. Would you be able to fix them as well?

**Comment by tknopp** [comment]
did not scroll further down :-)

**Comment by dkarrasch** [comment]
... and the `docs/make.jl` file, please. In the `deploydocs` function, there is another `/Jutho/LinearMaps.jl` where `Jutho` needs to be replaced by `JuliaLinearAlgebra`.

**Comment by dkarrasch** [comment]
I guess the documenter key needed an update. Let's see if it worked.

**Comment by dkarrasch** [comment]
Hm, the problem is that the documentation is not deployed because something is wrong with the deploy keys (though I tried to replace the keys with the new "owner" name `JuliaLinearAlgebra`). Does anybody know what adjustments need to be made after moving a repo? Maybe @ViralBShah knows (somebody who knows)?

**Comment by tknopp** [comment]
Do you expect deploying to work on a PR?

**Comment by dkarrasch** [comment]
I believe it used to deploy. We had a preview link to the new documentation in that box listing all the GHA steps. But you may be right. I could merge this and see what happens.

**Comment by dkarrasch** [comment]
Thanks for pushing me! 😝  Seems like it's working.

**Pull request merged**
