### PR TITLE
Update ci.yml for codecov v4

### PR DESCRIPTION
**Pull request by JeffFessler**
Hopefully addresses #228

### CODE REVIEW

**Comment by JeffFessler** [comment]
I have no idea why julia 1.6 for macOS failed.

**Comment by dkarrasch** [comment]
Could you please rebase onto current master? I relaxed the CI configuration a bit. I suspect that this works just fine, but would like to see some confirmation.

**Comment by JeffFessler** [comment]
Sadly I don't know how to do that, and I bet it will be faster for you to just close this PR and make a new PR than to teach me how!  And that's OK.  Is there is a github button I am overlooking for it?  I tried to RTFM:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-commits

**Comment by dkarrasch** [comment]
Indeed, I'm also missing that "rebase" button that I'm used to from the julia repo. @fredrikekre Do you know where to set this up?

I'll still share what I learnt from others in the community. After you updated your local `master` branch, you switch to the PR branch and then do

```
git pull --rebase origin master
```


to pull from master and rebase the current branch. Afterwards, you can resolve merge conflicts if necessary and then

```
git push --force
```

**Comment by dkarrasch** [comment]
I think I found the button.

**Comment by fredrikekre** [comment]
That is because this PR is from a fork and the secret is not available.

**Pull request merged**
