### PR TITLE
Add `EmbeddedMap`

### PR DESCRIPTION
**Pull request by dkarrasch**
This is a rebase of #65. Closes #65.

Dropping the requirement of monotonically increasing indices would allow to define "lazy" reversed maps, though negative strides in BLAS.gemv! is allowed starting from v1.8 only.

I wonder if `IndexMap` is the best name for it, though. "Index" is fairly generic, so we may want to spend some brain power to come up with a better name.

### CODE REVIEW

**Comment by dkarrasch** [comment]
If I'm not mistaken, then this PR coincides greatly with [`LiftedMaps.jl`](https://github.com/krcools/LiftedMaps.jl), so @krcools may want to take a look and make suggestions.

**Comment by dkarrasch** [comment]
Another thing: if one ignores the monotonic indices test, then this allows for lazy `reverse`al of matrices/maps! For matrices, that requires negative strides in BLAS, which is available only from v1.8, but still, another nice lazy feature.

**Comment by dkarrasch** [comment]
@krcools What do you think: I'm finding the name `IndexMap` too generic, so I was searching for other names, ideally with some precedence. Then I found your `LiftedMap`s, that has essentially the same functionality, and I assume some precedence regarding the name. What are your plans with your package? Do you think there is a possibility that we name the maps defined here as `LinearMaps.LiftedMap`s? Or shall we keep things independent and search for another name? It would be good to finish this and release it soon as v3.7, together with some of the other open PRs.

**Comment by krcools** [comment]
I am using LiftedMaps in my own registered projects and will keep doing so.  Functionality is indeed similar; a noteworthy difference is that LiftedMaps tries to be compatible with non-traditional axes (such as the blocked axes from BlockArrays).

I guess if the name is not exported both implementations can happily coexist.

Alternative names? Perhaps `ExtendedMaps`, `EmbeddedMaps`, `SingleBlockMaps`?

**Comment by dkarrasch** [comment]
Thanks for your feedback @krcools! Yes, we have avoided the dependency on BlockArrays.jl when we added the `BlockMap` functionality. I think I'll go with `EmbeddedMap`, that comes close to what I suggested in #134, which was closed in favor of the predecessor of this PR. Any name requires explanation, but `EmbeddedMap` comes with a little bit more context than just `IndexMap`.

**Pull request merged**
